---
build_from:
  aarch64: ghcr.io/hassio-addons/base:16.0.1
  amd64: ghcr.io/hassio-addons/base:16.0.1
  armhf: ghcr.io/hassio-addons/base:16.0.1
  armv7: ghcr.io/hassio-addons/base:16.0.1
  i386: ghcr.io/hassio-addons/base:16.0.1


# build_from:
#   aarch64: ghcr.io/sayam93/dash:latest
#   amd64: ghcr.io/sayam93/dash:latest
#   armhf: ghcr.io/sayam93/dash:latest
#   armv7: ghcr.io/sayam93/dash:latest
#   i386: ghcr.io/sayam93/dash:latest
# codenotary:
#   signer: codenotary@frenck.dev